### ISSUE TITLE
[Bug]Compile with spark3+ error in CreateViewCommand class

### ISSUE THREAD

**Issue by wengad82** [apache/incubator-linkis-website#292]
compile on spark 3.2.1, error log as following:

[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: /home/scm/.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.12-1.3.1-bin_2.12.15__52.0-1.3.1_20191012T045515.jar
[INFO] Compiling 64 Scala sources to /home/scm/comspace/Linkis/linkis-engineconn-plugins/engineconn-plugins/spark/target/classes ...
[ERROR] [Error] /home/scm/comspace/Linkis/linkis-engineconn-plugins/engineconn-plugins/spark/src/main/scala/org/apache/linkis/engineplugin/spark/metadata/SparkSQLHistoryParser.scala:218: value child is not a member of org.apache.spark.sql.execution.command.CreateViewCommand
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for linkis-engineconn-plugins 1.1.2:
[INFO] 
[INFO] linkis-engineconn-plugin-core ...................... SUCCESS [ 10.304 s]
[INFO] linkis-engineconn-plugin-cache ..................... SUCCESS [  1.152 s]
[INFO] linkis-engineconn-plugin-loader .................... SUCCESS [  5.736 s]
[INFO] linkis-engineconn-plugin-server .................... SUCCESS [ 54.806 s]
[INFO] linkis-engineplugin-hive ........................... SUCCESS [ 13.256 s]
[INFO] linkis-engineplugin-spark .......................... FAILURE [ 12.919 s]
[INFO] linkis-engineplugin-python ......................... SKIPPED
[INFO] linkis-engineplugin-openlookeng .................... SKIPPED
[INFO] linkis-engineplugin-io_file ........................ SKIPPED
[INFO] linkis-engineplugin-shell .......................... SKIPPED
[INFO] linkis-engineplugin-pipeline ....................... SKIPPED
[INFO] linkis-engineplugin-jdbc ........................... SKIPPED
[INFO] linkis-engineconn-plugins .......................... SKIPPED
[INFO] linkis-engineconn-plugin-flink ..................... SKIPPED
[INFO] linkis-engineplugin-sqoop .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:38 min
[INFO] Finished at: 2022-05-31T08:48:28+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.3.0:compile (scala-compile-first) on project linkis-engineplugin-spark: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.3.0:compile failed.: CompileFailed -> [Help 1]
[ERROR]

**Comment by casionone** [comment]
You can refer to this issue https://github.com/apache/incubator-linkis/issues/1412
In addition, about the linkis project, you should create an issue under this project   https://github.com/apache/incubator-linkis/issues
